Batchaioperator
cse-airflow/incubator-airflow pull request #8
Opened 2018-11-01 17:57 UTC by elizabethhalper

Make sure you have checked _all_ steps below.

### Jira

- [ ] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-3284\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-3284
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-3284\], code changes always need a Jira issue.

### Description

- [ ] Here are some details about my PR, including screenshots of any UI changes:
Add an operator to create an Azure Batch AI cluster. Azure Batch AI allows users to experiment and train deep learning and AI models in parallel at scale.

Operator supports creating a batch AI cluster by using any Marketplace image when given the publisher, offer, sku, and version.

### Tests

- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

There are unit tests that test a successful execution of the operator and an execution that raises an Airflow exception.

### Commits

- [ ] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality

- [ ] Passes `flake8`

2018-11-01 17:59 UTC, omusavi commented
Looks like there are still merge markers in the code

2018-11-01 18:37 UTC, elizabethhalper commented
@omusavi Sorry about that! I didn't realize they weren't deleted by auto-merging. I just went through and got rid of them.

2018-11-01 19:12 UTC, omusavi requested changes
Looks good overall, just a few things I think we need before merging

2018-11-01 19:12 UTC, omusavi commented on airflow/contrib/example_dags/example_batchai_dag.py
> +cmd = 'ls -l'
Remove if this is unused

2018-11-01 19:12 UTC, omusavi commented on airflow/contrib/operators/azure_batchai_operator.py
> +            username=os.environ['USERNAME'],
extraneous comma?

2018-11-01 19:12 UTC, omusavi commented on airflow/contrib/operators/azure_batchai_operator.py
> +                                           "container instance, retrying...")
Should string be updated?

2018-11-01 19:12 UTC, omusavi commented on docs/integration.rst
> + .. autoclass:: airflow.contrib.operators.azure_container_instances_operator.AzureContainerInstancesOperator
These class names need to be updated

2018-11-01 19:12 UTC, omusavi commented on airflow/contrib/operators/azure_batchai_operator.py
> +                                                        # AzureContainerRegistryHook,
Remove commented out classes

2018-11-01 19:12 UTC, omusavi commented on airflow/contrib/hooks/azure_batchai_hook.py
> +        instance_view = cluster[0]['properties'].get('instanceView', {})
can there be multiple clusters? Should we check to ensure there is at least 1? or >1 do we just do the first?

2018-11-01 20:08 UTC, omusavi approved these changes
Looks good!

2018-11-01 20:08 UTC, omusavi commented on tests/contrib/operators/test.py
> +# TEST SCRIPT BELOW
looks like an accidental add :)

2018-11-01 22:05 UTC, apraovjr commented
@elizabethhalper I think title and description should match with apache guidelines for PR no?

2018-11-01 22:17 UTC, elizabethhalper commented
@apraovjr I didn't think it would matter for our own repo but you're right, better to start now than have to change it later :)

2018-12-05 10:25 UTC, pchundi commented
@omusavi: Can you merge the PR if it meets your expectations? 
We would like to test this for a POC.

2018-12-05 11:46 UTC, omusavi commented
@pchundi I've already signed off but tests are not passing and are blocking merge

2018-12-05 12:13 UTC, elizabethhalper commented
@pchundi I will merge as soon as the tests are passing

2018-12-06 20:44 UTC, merged